#pragma once
#include <stdio.h>
#include <stdlib.h>
#include <iostream>
#include <string>
#include <fstream>
#include <map>
#include <list>
#include <glm/glm.hpp>
#include <SDL.h>
#include <gl/glew.h>
#include <json/json.h>